application: iceyapp-1077
version: 1
runtime: python27
api_version: 1
threadsafe: false

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
  
handlers:
- url: /static
  static_dir: static
  
- url: /.*
  script: iceywwg.py
  login: required
  
libraries:
- name: django
  version: "1.4"